# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 4
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_paramsA:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "CycleDense"
  ignore_label: 0
  return_test: False
  fixed_volume_space: False
  label_mapping: "./config/label_mapping/cycledense.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loaderA:
  data_path: "/home/jinwei/dense"
  imageset: "train"
  clss: "clear"
  return_ref: True
  batch_size: 2
  shuffle: True
  num_workers: 4


train_data_loaderB:
  data_path: "/home/jinwei/dense"
  imageset: "train"
  clss: "rain"
  return_ref: True
  batch_size: 2
  shuffle: True
  num_workers: 4


###################
## Train params
train_params:
  modelA2B_load_path: "/home/jinwei/Cylinder3D/model/modelA2B.pt"
  modelB2A_load_path: "/home/jinwei/Cylinder3D/model/modelB2A.pt"
  modelA2B_save_path: "/home/jinwei/Cylinder3D/model/modelA2B.pt"
  modelB2A_save_path: "/home/jinwei/Cylinder3D/model/modelB2A.pt"
  checkpoint_every_n_steps: 4599
  max_num_epochs: 40
  eval_every_n_steps: 4599
  learning_rate: 0.001
